triggers:
- envs: []
  name: 5am run
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-01-30 05:00:00
  status: inactive
  variables: {}
